# Generated by Django 5.0.7 on 2024-07-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
