# Generated by Django 5.0.7 on 2024-07-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='tasks',
        ),
    ]
